AWSTemplateFormatVersion: "2010-09-09"
Description: Discord Webhook Forwarder for CloudWatch Alarms (Python 3.12)

Transform: AWS::Serverless-2016-10-31

Parameters:
  DiscordWebhookUrl:
    Type: String
    NoEcho: true
    Description: Discord webhook URL

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-cloudwatch-alerts"
      DisplayName: "CloudWatch Alerts"

  DiscordWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {"statusCode": 200, "body": "OK"}
      Description: Forwards CloudWatch alarm notifications from SNS to Discord webhook
      Environment:
        Variables:
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
      Events:
        AlarmSNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref AlarmTopic

Outputs:
  FunctionName:
    Description: Lambda function name
    Value: !Ref DiscordWebhookFunction
  SnsTopicArn:
    Description: SNS Topic ARN to use in CloudWatch Alarms
    Value: !Ref AlarmTopic
